language: python
python:
  - "3.6"
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libssl-dev
    - python3-dev
    - swig
install:
# Install runtime dependencies from PyPI
  - pip install argcomplete
  - pip install attrdict
  - pip install cryptography
  - pip install empy
  - pip install lxml
  - pip install M2Crypto
  - pip install osrf_pycommon
  - pip install xmlschema
# Install ComArmor from git via master branch for profile language
  - pip install git+https://github.com/ComArmor/comarmor.git@master#egg=comarmor
# Install dependent keymint packages from git
  - pip install git+git://github.com/keymint/keymint_cli.git@master#egg=keymint_cli
  - pip install git+git://github.com/keymint/keymint_comarmor.git@master#egg=keymint_comarmor
  - pip install git+git://github.com/keymint/keymint_keymake.git@master#egg=keymint_keymake
  - pip install git+git://github.com/keymint/keymint_package.git@master#egg=keymint_package
  - pip install git+git://github.com/keymint/keymint_profile.git@master#egg=keymint_profile
# Install test dependencies from PyPI
  - pip install nose
  - pip install flake8 pydocstyle
# Install ament_copyright / ament_flake8 / ament_pep257 from git
  - cd /tmp
  - pip install --editable 'git+git://github.com/ament/ament_lint.git@master#egg=ament_copyright&subdirectory=ament_copyright'
  - pip install --editable 'git+git://github.com/ament/ament_lint.git@master#egg=ament_flake8&subdirectory=ament_flake8'
  - pip install --editable 'git+git://github.com/ament/ament_lint.git@master#egg=ament_pep257&subdirectory=ament_pep257'
script:
  - cd $TRAVIS_BUILD_DIR
  - python setup.py nosetests --nocapture
notifications:
  email: false
